# -*- coding: utf-8 -*-
"""Algoritmo guloso IC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQljuRFaLgqH8yScLJq9GXuQUvsnq92g

Bibliotecas
"""

import pandas as pd
from typing import Dict, List, Tuple, Any
import re

"""Função que carrega os dados das planilhas (estoque, demanda e entidades)"""

# @title
def carregar_estoque_planilha_controle(caminho: str) -> dict[str, dict[Any, Any]] | None:
    """
    Carrega dados de estoque a partir da planilha de controle de estoque da campanha
    """
    try:
        print("? Carregando planilha de estoque...")

        # Carregar a aba de movimenta��es (estoque1)
        df_mov = pd.read_excel(caminho, sheet_name="estoque1")

        print(f"   ? Aba 'estoque1' carregada com {len(df_mov)} linhas")
        print(f"   Colunas dispon�veis: {list(df_mov.columns)}")

        # Verificar se as colunas necess�rias existem
        col_quantidade = None
        col_operacao = None
        col_categoria = None
        col_genero = None

        # Mapear colunas
        for col in df_mov.columns:
            col_lower = str(col).lower()
            if 'quant' in col_lower and not col_operacao:
                col_quantidade = col
            elif 'opera' in col_lower or col_lower == 'd' or 'opera��o' in col_lower:
                col_operacao = col
            elif 'categoria' in col_lower or 'tipo' in col_lower:
                col_categoria = col
            elif 'genero' in col_lower or 'g�nero' in col_lower:
                col_genero = col

        # Se n�o encontrou, usar as colunas padr�o pelo nome exato
        if 'quantidade' in df_mov.columns:
            col_quantidade = 'quantidade'
        if 'Opera��o' in df_mov.columns:
            col_operacao = 'Opera��o'
        if 'categoria' in df_mov.columns:
            col_categoria = 'categoria'
        if 'genero' in df_mov.columns:
            col_genero = 'genero'

        print(f"   Coluna de quantidade: {col_quantidade}")
        print(f"   Coluna de opera��o: {col_operacao}")
        print(f"   Coluna de categoria: {col_categoria}")

        # Processar e limpar dados
        def limpar_valor(valor):
            """Converte valor para n�mero, tratando strings vazias e NAs"""
            if pd.isna(valor):
                return 0
            if isinstance(valor, (int, float)):
                return float(valor) if not pd.isna(valor) else 0
            if isinstance(valor, str):
                valor_limpo = valor.strip()
                if valor_limpo == '' or valor_limpo == '-' or valor_limpo == '0':
                    return 0
                try:
                    return float(valor_limpo)
                except:
                    return 0
            return 0

        # Aplicar limpeza na coluna de quantidade
        df_mov['quantidade_clean'] = df_mov[col_quantidade].apply(limpar_valor)

        # Calcular estoque por categoria (em pe�as)
        estoque_pecas = {}
        categorias_unicas = df_mov[col_categoria].dropna().unique()

        print(f"   Processando {len(categorias_unicas)} categorias...")

        for categoria in categorias_unicas:
            if pd.isna(categoria) or str(categoria).strip() == '':
                continue

            categoria_str = str(categoria).strip()

            # Filtrar entradas e sa�das
            mask_categoria = df_mov[col_categoria] == categoria

            # Calcular entradas
            mask_entrada = (mask_categoria) & (df_mov[col_operacao].astype(str).str.lower() == 'entrada')
            entradas = df_mov[mask_entrada]['quantidade_clean'].sum()

            # Calcular sa�das
            mask_saida = mask_categoria & (df_mov[col_operacao].astype(str).str.lower() == 'sa�da')
            saidas = df_mov[mask_saida]['quantidade_clean'].sum()

            estoque_pecas[categoria_str] = entradas - saidas

            if entradas > 0 or saidas > 0:
                print(f"      {categoria_str}: Entradas={entradas:.0f}, Sa�das={saidas:.0f}, Estoque={estoque_pecas[categoria_str]:.0f}")

        # Mapeamento de categoria para tamanho padr�o do conjunto (baseado na planilha)
        tamanhos_padrao = {
            "Camiseta manga longa feminina": 40,
            "Camiseta manga longa masculina": 40,
            "Cal�a Jeans feminina": 20,
            "Cal�a Jeans masculina": 20,
            "Cal�a N�o Jeans feminina": 20,
            "Cal�a N�o Jeans masculina": 20,
            "Manga Curta e regata feminina": 40,
            "Manga Curta e regata masculina": 40,
            "Infantil feminina": 40,
            "Infantil masculina": 40,
            "Pr�-adolescente feminina": 40,
            "Pr�-adolescente masculina": 40,
            "Shorts Feminino e Saia": 20,
            "Vestido/Macac�o": 40,
            "Agasalho Feminino": 10,
            "Agasalho Masculino": 10,
            "Pijama Feminino": 30,
            "Pijama Masculino": 30,
            "Shorts feminino e saia": 30,
            "Shorts masculino e bermuda": 30,
            "Sapatos Feminino": 20,
            "Sapatos Masculino": 20,
            "Acess�rios Gerais": 20,
            "Acess�rios de Inverno": 25,
            "Beb�": 40,
            "Meias": 30,
            "Cobertor": 5,
            "Cama, Mesa e Banho": 20,
            "Brinquedos": 10,
            "Sapatos Infanto Juvenil": 25,
            "Extragrande": 20,
            "MANGA CURTA E REGATA": 40,
            "MANGA LONGA": 40,
            "CAL�AS JEANS": 15,
            "CAL�AS N�O JEANS": 20,
            "SHORTS E BERMUDA": 30,
            "SHORTS E SAIA": 30,
            "AGASALHO": 20,
            "PIJAMA": 30,
            "VESTIDO E MACAC�O": 40,
            "BEB�": 40,
            "INFANTIL (3-9)": 40,
            "PR�-ADOLESCENTE (10-15)": 40,
            "SAPATOS": 20,
            "SAPATOS INFANTO JUVENIL": 25,
            "ACESS�RIOS GERAIS": 20,
            "ACESS�RIOS DE INVERNO": 25,
            "MEIAS": 30,
            "COBERTOR": 5,
            "CAMA, MESA E BANHO": 20,
            "BRINQUEDOS": 10,
            "EXTRAGRANDE": 20
        }

        estoque_conjuntos = {}
        tamanho_conjunto = {}

        # Converter pe�as para conjuntos
        for categoria, pecas in estoque_pecas.items():
            # Buscar tamanho do conjunto
            tamanho = tamanhos_padrao.get(categoria, 1)

            # Ajustar tamanho baseado no nome da categoria
            if 'cal�a' in categoria.lower() or 'shorts' in categoria.lower() or 'saia' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'manga' in categoria.lower():
                if tamanho == 1:
                    tamanho = 40
            elif 'agasalho' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'pijama' in categoria.lower():
                if tamanho == 1:
                    tamanho = 30
            elif 'sapato' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'acess�rio' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'meia' in categoria.lower():
                if tamanho == 1:
                    tamanho = 30
            elif 'cobertor' in categoria.lower():
                if tamanho == 1:
                    tamanho = 5
            elif 'cama' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'brinquedo' in categoria.lower():
                if tamanho == 1:
                    tamanho = 10

            # Calcular n�mero de conjuntos
            if pecas > 0:
                conjuntos = int(pecas // tamanho)
                if conjuntos > 0 or pecas > 0:
                    estoque_conjuntos[categoria] = conjuntos
                    tamanho_conjunto[categoria] = tamanho
                    print(f"      {categoria}: {pecas:.0f} pe�as -> {conjuntos} conjuntos de {tamanho} pe�as")

        print(f"\n? Processadas {len(estoque_conjuntos)} categorias de roupa")
        print(f"  Total de conjuntos em estoque: {sum(estoque_conjuntos.values())}")
        print(f"  Total de pe�as em estoque: {sum(estoque_pecas.values()):.0f}")

        return {
            'estoque_conjuntos': estoque_conjuntos,
            'tamanho_conjunto': tamanho_conjunto,
            'estoque_pecas': estoque_pecas
        }

    except Exception as e:
        print(f"? Erro ao carregar planilha de estoque: {e}")
        import traceback
        traceback.print_exc()
        return None

def carregar_entidades_planilha_entidades(caminho: str) -> List[str]:
    """
    Carrega lista de entidades a partir da planilha de entidades da campanha
    """
    try:
        print("\n? Carregando planilha de entidades...")
        entidades = set()

        palavras_invalidas = [
            'n�o', 'sim', 'as vezes', 'caso necess�rio', 'autorizamos',
            'familias', 'pessoas', 'crian�as', 'adolescentes', 'beb�s',
            'media', 'm�dia', 'aproximadamente', 'total', 'quantidade'
        ]

        # Carregar todas as abas
        xl = pd.ExcelFile(caminho)
        sheets = xl.sheet_names

        print(f"   Abas encontradas: {sheets}")

        for sheet in sheets:
            if sheet in ['VG_NEW', 'Informa��es Entidades']:
                df = pd.read_excel(caminho, sheet_name=sheet, header=1)
                print(f"   Processando aba '{sheet}' com {len(df)} linhas")

                for col in df.columns:
                    col_str = str(col)
                    # Procura APENAS colunas que s�o explicitamente de nome da entidade
                    if col_str.lower() in ['entidade', 'nome da entidade']:
                        for valor in df[col].dropna():
                            valor_str = str(valor).strip()
                            # Filtros para considerar apenas entidades v�lidas
                            if (valor_str and
                                not valor_str.startswith('=IFERROR') and
                                len(valor_str) > 5 and
                                not any(palavra in valor_str.lower() for palavra in palavras_invalidas) and
                                not valor_str.isdigit() and  # N�o � apenas n�mero
                                not valor_str.replace(' ', '').isdigit()):  # N�o � "20" ou "20 familias"
                                entidades.add(valor_str)
                                print(f"      Entidade encontrada: {valor_str[:50]}")

        # Tamb�m carregar das abas de respostas
        for sheet in ['resp20252', 'resp20251', 'resp20242', 'resp20241']:
            if sheet in sheets:
                df = pd.read_excel(caminho, sheet_name=sheet)

                for col in df.columns:
                    col_str = str(col)
                    # Procura APENAS a coluna 'Nome da entidade'
                    if col_str == 'Nome da entidade':
                        for valor in df[col].dropna():
                            valor_str = str(valor).strip()
                            if (valor_str and
                                not valor_str.startswith('=IFERROR') and
                                len(valor_str) > 5 and
                                not any(palavra in valor_str.lower() for palavra in palavras_invalidas)):
                                entidades.add(valor_str)
                                print(f"      Entidade encontrada: {valor_str[:50]}")

        entidades_lista = sorted(list(entidades))
        print(f"\n? Total de entidades carregadas: {len(entidades_lista)}")

        if entidades_lista:
            print("   Entidades encontradas:")
            for i, ent in enumerate(entidades_lista[:20], 1):
                print(f"      {i}. {ent}")
            if len(entidades_lista) > 20:
                print(f"      ... e mais {len(entidades_lista) - 20} entidades")

        return entidades_lista

    except Exception as e:
        print(f"? Erro ao carregar planilha de entidades: {e}")
        import traceback
        traceback.print_exc()
        return []

def carregar_demandas_planilha_entidades(caminho: str,
                                          estoque_conjuntos: Dict[str, int],
                                          tamanho_conjunto: Dict[str, int],
                                          usar_pesos_personalizados: bool = True) -> Tuple[Dict, Dict]:
    """
    Carrega demandas e calcula pesos de prioridade personalizados
    Entidades que informaram pessoas usam 2 pe�as/pessoa
    Entidades que N�O informaram usam 5 pe�as/pessoa (estimativa com 50 pessoas)
    """
    try:
        print("\n? Carregando demandas e calculando pesos das entidades...")

        xl = pd.ExcelFile(caminho)
        sheets = xl.sheet_names

        demandas_conjuntos = {}
        prioridades = {}

        PECAS_POR_PESSOA_REAL = 2      # Para entidades que informaram pessoas
        PECAS_POR_PESSOA_ESTIMADO = 5  # Para entidades que N�O informaram
        PESSOAS_PADRAO = 50            # Valor padr�o quando n�o informado o numero de pessoas de cada entidade

        # Mapeamento de categorias
        mapeamento_categorias = {
            'Cal�a jeans': ['CAL�AS JEANS', 'Cal�a Jeans feminina', 'Cal�a Jeans masculina'],
            'Cal�a n�o jeans': ['CAL�AS N�O JEANS', 'Cal�a N�o Jeans feminina', 'Cal�a N�o Jeans masculina'],
            'Shorts e bermudas': ['SHORTS E BERMUDA', 'Shorts masculino e bermuda'],
            'Shorts e saia': ['SHORTS E SAIA', 'Shorts Feminino e Saia', 'Shorts feminino e saia'],
            'Agasalhos': ['AGASALHO', 'Agasalho Feminino', 'Agasalho Masculino'],
            'Manga curta e regata': ['MANGA CURTA E REGATA', 'Manga Curta e regata feminina', 'Manga Curta e regata masculina'],
            'Manga longa': ['MANGA LONGA', 'Camiseta manga longa feminina', 'Camiseta manga longa masculina'],
            'Pijamas': ['PIJAMA', 'Pijama Feminino', 'Pijama Masculino'],
            'Sapatos': ['SAPATOS', 'Sapatos Feminino', 'Sapatos Masculino'],
            'Acess�rios de inverno': ['ACESS�RIOS DE INVERNO'],
            'Meias': ['MEIAS'],
            'Cobertores': ['COBERTOR'],
            'Cama, mesa e banho': ['CAMA, MESA E BANHO'],
            'Brinquedos': ['BRINQUEDOS'],
            'Sapatos infantis': ['SAPATOS INFANTO JUVENIL'],
            'Roupas infantis': ['INFANTIL (3-9)', 'Infantil feminina', 'Infantil masculina'],
            'Roupas para beb�s': ['BEB�'],
            'Extra grande': ['EXTRAGRANDE'],
            'Roupas para pr�-adolescentes': ['PR�-ADOLESCENTE (10-15)', 'Pr�-adolescente feminina', 'Pr�-adolescente masculina'],
            'Vestidos': ['VESTIDO/MACAC�O', 'Vestido/Macac�o']
        }

        # Abas de respostas
        resp_sheets = ['resp20252', 'resp20251', 'resp20242', 'resp20241']

        # Coletar todas as entidades v�lidas
        entidades_validas = set()
        for sheet in resp_sheets:
            if sheet in sheets:
                df = pd.read_excel(caminho, sheet_name=sheet)
                for col in df.columns:
                    if 'entidade' in str(col).lower() or 'nome' in str(col).lower():
                        for valor in df[col].dropna():
                            nome = str(valor).strip()
                            if nome and not nome.startswith('=IFERROR') and len(nome) > 5:
                                entidades_validas.add(nome)

        # Contadores para estat�sticas
        entidades_com_pessoas = 0
        entidades_sem_pessoas = 0
        total_demandas_calculadas = 0

        # Processar cada aba de respostas
        for sheet in resp_sheets:
            if sheet in sheets:
                df = pd.read_excel(caminho, sheet_name=sheet)
                print(f"   Processando aba '{sheet}'...")

                # Identificar colunas
                col_entidade = None
                col_categorias = None
                col_quantidade_pessoas = None
                col_nivel_necessidade = None
                col_categorias_prioritarias = None

                for col in df.columns:
                    col_str = str(col).lower()
                    if 'entidade' in col_str and not col_entidade:
                        col_entidade = col
                    elif ('categoria' in col_str or 'roupas' in col_str) and 'necessitam' in col_str:
                        if 'mais' in col_str or 'priorit' in col_str:
                            col_categorias_prioritarias = col
                        else:
                            col_categorias = col
                    elif 'pessoas' in col_str or 'assistidas' in col_str or 'atendidas' in col_str:
                        col_quantidade_pessoas = col
                    elif ('quantidade' in col_str or 'n�vel' in col_str or 'necessidade' in col_str) and 'roupas' in col_str:
                        col_nivel_necessidade = col

                if not col_nivel_necessidade:
                    for col in df.columns:
                        col_str = str(col).lower()
                        if any(word in col_str for word in ['muito', 'pouco', 'necessidade', 'urgente']):
                            col_nivel_necessidade = col
                            break

                if not col_categorias_prioritarias:
                    for col in df.columns:
                        col_str = str(col).lower()
                        if any(word in col_str for word in ['priorit', 'mais precisa', 'categoria mais']):
                            col_categorias_prioritarias = col
                            break

                if col_entidade and col_categorias:
                    print(f"      Coluna entidade: {col_entidade}")
                    print(f"      Coluna n�vel necessidade: {col_nivel_necessidade if col_nivel_necessidade else 'N�o encontrada'}")
                    print(f"      Coluna categorias priorit�rias: {col_categorias_prioritarias if col_categorias_prioritarias else 'N�o encontrada'}")

                    # Calcular pesos personalizados
                    if usar_pesos_personalizados and col_nivel_necessidade and col_categorias_prioritarias:
                        pesos_aba = calcular_pesos_prioridade(
                            df, col_entidade, col_nivel_necessidade,
                            col_categorias_prioritarias,
                            list(estoque_conjuntos.keys()),
                            mapeamento_categorias
                        )
                        prioridades.update(pesos_aba)

                    # Processar demandas
                    for idx, row in df.iterrows():
                        entidade = str(row[col_entidade]) if pd.notna(row[col_entidade]) else ''
                        if not entidade or entidade.startswith('=IFERROR') or len(entidade) < 5:
                            continue

                        if entidade not in entidades_validas:
                            continue

                        categorias_str = str(row[col_categorias]) if pd.notna(row[col_categorias]) else ''

                        # extraindo quantidade de pessoas da planilha
                        qtd_pessoas = 0
                        entidade_informou_pessoas = False

                        if col_quantidade_pessoas and pd.notna(row[col_quantidade_pessoas]):
                            try:
                                pessoas_str = str(row[col_quantidade_pessoas])
                                # Tenta extrair o primeiro n�mero encontrado
                                numeros = re.findall(r'\d+', pessoas_str)
                                if numeros:
                                    qtd_pessoas = int(numeros[0])
                                    entidade_informou_pessoas = True
                            except:
                                pass


                        if entidade_informou_pessoas:
                            # Entidade informou o n�mero de pessoas
                            pecas_por_pessoa = PECAS_POR_PESSOA_REAL
                            demanda_pecas = int(qtd_pessoas * pecas_por_pessoa)
                            tipo_demanda = "REAL"
                            entidades_com_pessoas += 1
                        else:
                            # Entidade N�O informou - estimativa
                            qtd_pessoas = PESSOAS_PADRAO
                            pecas_por_pessoa = PECAS_POR_PESSOA_ESTIMADO
                            demanda_pecas = int(qtd_pessoas * pecas_por_pessoa)
                            tipo_demanda = "ESTIMADA"
                            entidades_sem_pessoas += 1

                        # Para cada tipo de roupa
                        for tipo_estoque in estoque_conjuntos.keys():
                            needs_match = False
                            for key, mapped_types in mapeamento_categorias.items():
                                if key in categorias_str or key.lower() in categorias_str.lower():
                                    if tipo_estoque in mapped_types or any(mt in tipo_estoque for mt in mapped_types):
                                        needs_match = True
                                        break

                            if needs_match or 'todas' in categorias_str.lower() or 'todos' in categorias_str.lower():
                                tamanho = tamanho_conjunto.get(tipo_estoque, 1)

                                # Converte pe�as para conjuntos (arredondando para cima)
                                demanda_conjuntos_calc = demanda_pecas // tamanho
                                demanda_conjuntos_calc = max(demanda_conjuntos_calc, 0)

                                chave = (tipo_estoque, entidade)

                                # Se j� existe demanda para esta combina��o, mant�m a maior
                                if chave not in demandas_conjuntos:
                                    demandas_conjuntos[chave] = demanda_conjuntos_calc
                                    total_demandas_calculadas += 1

                                    if chave not in prioridades:
                                        prioridades[chave] = 1.0


        print(f"\n? Total de demandas em CONJUNTOS: {len(demandas_conjuntos)}")
        print(f"? Total de pesos personalizados calculados: {len(prioridades)}")
        print(f"\n? Estat�sticas de c�lculo de demanda:")
        print(f"   Entidades que INFORMARAM pessoas: {entidades_com_pessoas} (usaram {PECAS_POR_PESSOA_REAL} pe�as/pessoa)")
        print(f"   Entidades que N�O informaram pessoas: {entidades_sem_pessoas} (usaram {PECAS_POR_PESSOA_ESTIMADO} pe�as/pessoa)")

        # Estatisticas totais
        total_demanda_conj = sum(demandas_conjuntos.values())
        total_demanda_pecas = 0
        for (tipo, _), conj in demandas_conjuntos.items():
            total_demanda_pecas += conj * tamanho_conjunto.get(tipo, 1)

        total_estoque_conj = sum(estoque_conjuntos.values())
        total_estoque_pecas = sum(estoque_conjuntos.get(tipo, 0) * tamanho_conjunto.get(tipo, 1)
                                   for tipo in estoque_conjuntos.keys())

        print(f"\n   Demanda total: {total_demanda_conj} conjuntos ({total_demanda_pecas:.0f} pe�as)")
        print(f"   Estoque total: {total_estoque_conj} conjuntos ({total_estoque_pecas:.0f} pe�as)")
        print(f"   Rela��o demanda/estoque: {total_demanda_conj / max(1, total_estoque_conj):.1f}x")

        return demandas_conjuntos, prioridades

    except Exception as e:
        print(f"? Erro ao carregar demandas: {e}")
        import traceback
        traceback.print_exc()
        return {}, {}

"""função que avalia os pesos conforme a resposta da planilha"""

# @title
def calcular_pesos_prioridade(df_resposta: pd.DataFrame,
                               col_entidade: str,
                               col_quantidade: str,
                               col_categorias: str,
                               tipos_roupa_disponiveis: List[str],
                               mapeamento_categorias: Dict) -> Dict:
    """
    Calcula pesos de prioridade baseado na necessidade da entidade

    Args:
        df_resposta: DataFrame com as respostas da entidade
        col_entidade: Nome da coluna com nome da entidade
        col_quantidade: Nome da coluna com n�vel de necessidade (muito/pouco)
        col_categorias: Nome da coluna com categorias mais necessitadas
        tipos_roupa_disponiveis: Lista de tipos de roupa dispon�veis no estoque
        mapeamento_categorias: Mapeamento entre categorias do forms e estoque
        PESO PADR�O = 1.0

    Returns:
        Dicion�rio com pesos para cada (tipo_roupa, entidade)
    """
    pesos = {}

    # Mapeamento do n�vel de necessidade para peso base
    # Quanto maior a necessidade, maior o peso
    peso_por_necessidade = {
        'muito': 2.5,
        'muita': 2.5,
        'alta': 2.5,
        'urgente': 3.0,
        'm�dio': 2.0,
        'media': 2.0,
        'm�dia': 2.0,
        'pouco': 1.0,
        'baixa': 1.0,
        'normal': 1.5,
        'regular': 1.5
    }

    for idx, row in df_resposta.iterrows():
        entidade = str(row[col_entidade]) if pd.notna(row[col_entidade]) else ''
        if not entidade or entidade.startswith('=IFERROR') or len(entidade) < 5:
            continue

        # 1. Peso base pelo n�vel de necessidade
        necessidade_texto = str(row[col_quantidade]) if pd.notna(row[col_quantidade]) else 'normal'
        necessidade_texto = necessidade_texto.lower().strip()

        peso_base = 1.0  # peso padr�o
        for key, value in peso_por_necessidade.items():
            if key in necessidade_texto:
                peso_base = value
                break

        # 2. Identificar categorias priorit�rias da entidade
        categorias_prioritarias = str(row[col_categorias]) if pd.notna(row[col_categorias]) else ''
        categorias_prioritarias = categorias_prioritarias.lower()

        # Lista de categorias que a entidade mais precisa
        categorias_prioritarias_lista = []
        for cat_form, cat_estoque_list in mapeamento_categorias.items():
            if cat_form.lower() in categorias_prioritarias:
                categorias_prioritarias_lista.extend(cat_estoque_list)

        # 3. Calcular peso final para cada tipo de roupa
        for tipo_roupa in tipos_roupa_disponiveis:
            # Peso base pela necessidade geral
            peso_final = peso_base

            # Aumenta peso se for uma categoria priorit�ria para esta entidade
            if tipo_roupa in categorias_prioritarias_lista:
                # Categoria priorit�ria ganha peso extra
                peso_final *= 2.5
            elif any(cat in tipo_roupa.lower() for cat in ['acess�rio', 'brinquedo', 'cobertor']):
                # Itens complementares t�m peso reduzido
                peso_final *= 1.5
            else:
                # Demais categorias mant�m peso base
                peso_final *= 1.0

            # Garantir que o peso esteja em um range razo�vel
            peso_final = max(1, min(5.0, peso_final))

            chave = (tipo_roupa, entidade)
            pesos[chave] = peso_final


    return pesos

"""Algoritmo guloso"""

# @title
def algoritmo_guloso_por_prioridade_item(estoque: Dict[str, int],
                                          demandas: Dict[Tuple[str, str], int],
                                          prioridades: Dict[Tuple[str, str], float]) -> Tuple[Dict, Dict]:
    """
    Distribui respeitando a prioridade vinda das demandas
    """

    estoque_atual = estoque.copy()

    # Criar lista de todos os pedidos com suas prioridades
    pedidos = []
    for (tipo, entidade), demanda in demandas.items():
        peso = prioridades.get((tipo, entidade), 1.0)
        pedidos.append((peso, tipo, entidade, demanda))

    # Ordenar por prioridade (maior primeiro) - CRITÉRIO GULOSO
    pedidos.sort(key=lambda x: x[0], reverse=True)

    distribuicao = {}

    print("\n=== DISTRIBUIÇÃO POR PRIORIDADE INDIVIDUAL ===\n")

    for peso, tipo, entidade, demanda in pedidos:
        disponivel = estoque_atual.get(tipo, 0)

        if disponivel > 0:
            atendido = min(demanda, disponivel)
            estoque_atual[tipo] -= atendido

            if atendido > 0:
                if entidade not in distribuicao:
                    distribuicao[entidade] = {}
                distribuicao[entidade][tipo] = atendido

                status = "COMPLETO" if atendido == demanda else "PARCIAL"
                print(f"[Peso:{peso:.2f}] {entidade} - {tipo}: {status} ({atendido}/{demanda})")

    return distribuicao, estoque_atual

"""função que gera o relatório"""

# @title
def gerar_relatorio_distribuicao(distribuicao: Dict,
                                  estoque_final: Dict,
                                  estoque_inicial: Dict,
                                  demandas: Dict,
                                  prioridades: Dict,
                                  tamanho_conjunto: Dict) -> Dict:
    """
    Gera relatório completo da distribuição
    """
    # Entidades atendidas
    entidades_atendidas = [e for e in distribuicao if distribuicao[e]]

    # Total distribuído
    total_conjuntos_distribuidos = sum(
        sum(item.values()) for item in distribuicao.values()
    )

    total_pecas_distribuidas = 0
    for entidade, itens in distribuicao.items():
        for tipo, qtd in itens.items():
            total_pecas_distribuidas += qtd * tamanho_conjunto.get(tipo, 1)

    # Estoque restante
    total_conjuntos_restantes = sum(estoque_final.values())
    total_pecas_restantes = sum(
        qtd * tamanho_conjunto.get(tipo, 1) for tipo, qtd in estoque_final.items()
    )

    # Estoque inicial
    total_conjuntos_inicial = sum(estoque_inicial.values())

    # Taxa de atendimento
    taxa_atendimento = (total_conjuntos_distribuidos / total_conjuntos_inicial * 100) if total_conjuntos_inicial > 0 else 0

    # Relatório
    relatorio = {
        'resumo': {
            'entidades_atendidas': len(entidades_atendidas),
            'total_conjuntos_distribuidos': total_conjuntos_distribuidos,
            'total_pecas_distribuidas': total_pecas_distribuidas,
            'total_conjuntos_restantes': total_conjuntos_restantes,
            'total_pecas_restantes': total_pecas_restantes,
            'taxa_atendimento_estoque': f"{taxa_atendimento:.1f}%"
        },
        'detalhes_entidades': {},
        'estoque_restante_detalhado': estoque_final
    }

    # Detalhes por entidade
    for entidade, itens in distribuicao.items():
        if itens:
            total_conjuntos = sum(itens.values())
            total_pecas = sum(
                qtd * tamanho_conjunto.get(tipo, 1) for tipo, qtd in itens.items()
            )
            relatorio['detalhes_entidades'][entidade] = {
                'itens_recebidos': itens,
                'total_conjuntos': total_conjuntos,
                'total_pecas': total_pecas
            }

    # Imprimir relatório formatado
    print("\n" + "="*60)
    print("RELATÓRIO FINAL DA DISTRIBUIÇÃO")
    print("="*60)

    print(f"\n📊 RESUMO:")
    print(f"   ✅ Entidades atendidas: {relatorio['resumo']['entidades_atendidas']}")
    print(f"   📦 Conjuntos distribuídos: {relatorio['resumo']['total_conjuntos_distribuidos']}")
    print(f"   👕 Peças distribuídas: {relatorio['resumo']['total_pecas_distribuidas']:.0f}")
    print(f"   📦 Conjuntos restantes: {relatorio['resumo']['total_conjuntos_restantes']}")
    print(f"   👕 Peças restantes: {relatorio['resumo']['total_pecas_restantes']:.0f}")
    print(f"   📈 Taxa de utilização: {relatorio['resumo']['taxa_atendimento_estoque']}")

"""executora e main"""

def executar_distribuicao_gulosa(caminho_planilha_estoque: str,
                                  caminho_planilha_entidades: str,
                                  usar_pesos_personalizados: bool = True,
                                  ignorar_tamanho_um: bool = True) -> Dict:
    """
    Executa o algoritmo guloso completo de distribuição de doações

    Args:
        caminho_planilha_estoque: caminho da planilha com controle de estoque
        caminho_planilha_entidades: caminho da planilha com entidades e demandas
        usar_pesos_personalizados: se True, calcula pesos baseado nas respostas
        ignorar_tamanho_um: se True, remove categorias com tamanho de conjunto = 1 (peças avulsas)
    """

    print("="*60)
    print("INICIANDO ALGORITMO GULOSO DE DISTRIBUIÇÃO")
    print("="*60)

    # 1. Carregar estoque da planilha de controle
    print("\n[1/3] Carregando estoque...")
    dados_estoque = carregar_estoque_planilha_controle(caminho_planilha_estoque)

    if not dados_estoque:
        print("❌ Erro: Não foi possível carregar o estoque!")
        return None

    estoque_conjuntos = dados_estoque['estoque_conjuntos']
    tamanho_conjunto = dados_estoque['tamanho_conjunto']

    if ignorar_tamanho_um:
        print("\n Removendo categorias com tamanho de conjunto = 1 (peças avulsas)...")

        categorias_removidas = []
        categorias_filtradas = {}
        tamanho_filtrado = {}

        for categoria, qtd in estoque_conjuntos.items():
            tamanho = tamanho_conjunto.get(categoria, 1)
            if tamanho > 1:
                categorias_filtradas[categoria] = qtd
                tamanho_filtrado[categoria] = tamanho
            else:
                categorias_removidas.append(f"{categoria} (tamanho={tamanho}, {qtd} conjuntos)")

        # Substituir pelos dados filtrados
        estoque_conjuntos = categorias_filtradas
        tamanho_conjunto = tamanho_filtrado

        print(f"   ✓ Categorias mantidas: {len(estoque_conjuntos)}")
        print(f"   ✓ Categorias removidas: {len(categorias_removidas)}")
        if categorias_removidas:
            print(f"   ✓ Removidas: {', '.join(categorias_removidas[:5])}")
            if len(categorias_removidas) > 5:
                print(f"     ... e mais {len(categorias_removidas) - 5} categorias")
        print(f"   ✓ Total de conjuntos após filtro: {sum(estoque_conjuntos.values())}")

    print(f"\n✓ Estoque carregado: {len(estoque_conjuntos)} categorias, {sum(estoque_conjuntos.values())} conjuntos")

    # 2. Carregar demandas e prioridades da planilha de entidades
    print("\n[2/3] Carregando demandas e prioridades...")
    demandas, prioridades = carregar_demandas_planilha_entidades(
        caminho_planilha_entidades,
        estoque_conjuntos,
        tamanho_conjunto,
        usar_pesos_personalizados=usar_pesos_personalizados
    )

    if not demandas:
        print("❌ Erro: Nenhuma demanda encontrada!")
        return None

    print(f"✓ Demandas carregadas: {len(demandas)} pedidos")
    print(f"✓ Prioridades calculadas: {len(prioridades)} combinações")

    # 3. Executar algoritmo guloso
    print("\n[3/3] Executando algoritmo guloso...")
    distribuicao, estoque_final = algoritmo_guloso_por_prioridade_item(
        estoque_conjuntos, demandas, prioridades
    )

    # 4. Gerar relatório
    print("\n[4/4] Gerando relatório...")
    relatorio = gerar_relatorio_distribuicao(
        distribuicao, estoque_final, estoque_conjuntos,
        demandas, prioridades, tamanho_conjunto
    )

    print("\n" + "="*60)
    print("DISTRIBUIÇÃO CONCLUÍDA!")
    print("="*60)

    return {
        'distribuicao': distribuicao,
        'estoque_final': estoque_final,
        'relatorio': relatorio,
        'demandas': demandas,
        'prioridades': prioridades
    }


def main():
    """
    Função principal que executa todo o fluxo
    """

    CAMINHO_PLANILHA_ESTOQUE = "controle estoque campanha.xlsx"
    CAMINHO_PLANILHA_ENTIDADES = "entidades campanha.xlsx"

    # Parâmetros do algoritmo
    USAR_PESOS_PERSONALIZADOS = True   # Usar pesos das respostas das entidades
    IGNORAR_TAMANHO_UM = True

    print("\n" + "🔹"*30)
    print("ALGORITMO GULOSO PARA DISTRIBUIÇÃO DE DOAÇÕES")
    print("🔹"*30)

    # Executar distribuição
    resultado = executar_distribuicao_gulosa(
        caminho_planilha_estoque=CAMINHO_PLANILHA_ESTOQUE,
        caminho_planilha_entidades=CAMINHO_PLANILHA_ENTIDADES,
        usar_pesos_personalizados=USAR_PESOS_PERSONALIZADOS,
        ignorar_tamanho_um=IGNORAR_TAMANHO_UM
    )

    if resultado:
        # Perguntar se quer salvar os resultados
        try:
            salvar_resultados = input("\n💾 Deseja salvar os resultados em arquivo? (s/n): ").lower()
        except:
            salvar_resultados = 'n'
            print("\n⚠ Executando em ambiente sem input - não salvando arquivos")

        if salvar_resultados == 's':
            # Salvar distribuição em CSV
            df_distribuicao = []
            for entidade, itens in resultado['distribuicao'].items():
                for tipo, qtd in itens.items():
                    df_distribuicao.append({
                        'Entidade': entidade,
                        'Tipo de Roupa': tipo,
                        'Conjuntos Recebidos': qtd
                    })

            if df_distribuicao:
                df = pd.DataFrame(df_distribuicao)
                df.to_csv('distribuicao_realizada.csv', index=False, encoding='utf-8-sig')
                print("✓ Distribuição salva em 'distribuicao_realizada.csv'")

            # Salvar estoque final
            df_estoque = pd.DataFrame([
                {'Tipo': tipo, 'Conjuntos_Restantes': qtd}
                for tipo, qtd in resultado['estoque_final'].items()
            ])
            df_estoque.to_csv('estoque_final.csv', index=False, encoding='utf-8-sig')
            print("✓ Estoque final salvo em 'estoque_final.csv'")

        return resultado
    else:
        print("❌ Falha na execução do algoritmo!")
        return None


# ==================== EXECUTAR ====================
if __name__ == "__main__":
    resultado = main()