# -*- coding: utf-8 -*-
"""solver-final-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Dani-ela-git/8a241f26e4191f8130d3094e43e07ff3/solver-final-2.ipynb

Ação necessária para montar o drive
"""

#from google.colab import drive
#drive.mount('/content/drive')

"""Biblioteca"""

# @title
import numpy as np
import pulp
import pandas as pd
import os
import re
import random
import time
from typing import Dict, List, Tuple, Optional
from datetime import datetime
import unicodedata

"""Criando a classe com a função objetivo maximizando o total de peças alocado"""

# @title
class AlocacaoConjuntosSolver:
    """
    Classe para resolver problema adaptado para a Campanha do Agasalho
    Maximiza a alocação total com pesos
    """

    def __init__(self, nome_problema: str = 'Alocacao_Conjuntos'):
        self.nome_problema = nome_problema
        self.problema = None
        self.variaveis = {}
        self.resultados = None

        # Dados do problema
        self.tipos_roupa = []
        self.entidades = []
        self.estoque_conjuntos = {}
        self.tamanho_conjunto = {}
        self.demandas_pecas = {}
        self.peso_prioridade = {}

    def definir_problema(self,
                         tipos_roupa: List[str],
                         entidades: List[str],
                         estoque_conjuntos: Dict[str, int],
                         tamanho_conjunto: Dict[str, int],
                         demandas_conjuntos: Dict[Tuple[str, str], int],
                         peso_prioridade: Dict[Tuple[str, str], float]) -> None:
        """
        Define os dados do problema com a nova estrutura usando conjuntos
        """
        self.tipos_roupa = tipos_roupa
        self.entidades = entidades
        self.estoque_conjuntos = estoque_conjuntos
        self.tamanho_conjunto = tamanho_conjunto
        self.demandas_conjuntos = demandas_conjuntos
        self.peso_prioridade = peso_prioridade

    def criar_variaveis(self):
        """
        Cria as variáveis de decisão.
        X_{tipo}_{entidade} = número de CONJUNTOS alocados
        """
        for tipo in self.tipos_roupa:
            for entidade in self.entidades:
                nome_variavel = f"X_{tipo}_{entidade}"
                chave = (tipo, entidade)

                max_conjuntos = 0 # Initialize max_conjuntos
                if chave in self.demandas_conjuntos:
                     # Limite superior baseado na demanda em CONJUNTOS
                  max_conjuntos = self.demandas_conjuntos[chave]

                if max_conjuntos > 0:
                    self.variaveis[nome_variavel] = pulp.LpVariable(
                        name=nome_variavel,
                        lowBound=0,
                        upBound=None,
                        cat='Integer'
                    )
                else:
                    self.variaveis[nome_variavel] = pulp.LpVariable(
                        name=nome_variavel,
                        lowBound=0,
                        upBound=0,
                        cat='Integer'
                    )

        print(f"Variáveis criadas: {len(self.variaveis)} variáveis")

    def criar_restricoes(self):
        """
        Cria as restrições do problema
        """
        print("\nCriando restrições...")

        # Restrição 1: Estoque em conjuntos
        print("1. Restrição de estoque por tipo de roupa (em conjuntos):")
        for tipo in self.tipos_roupa:
            soma_conjuntos = pulp.lpSum([
                self.variaveis[f"X_{tipo}_{entidade}"]
                for entidade in self.entidades
                if f"X_{tipo}_{entidade}" in self.variaveis
            ])
            self.problema += soma_conjuntos <= self.estoque_conjuntos.get(tipo, 0), f"Estoque_Conjuntos_{tipo}"
            #print(f"Tipo {tipo}: ∑ conjuntos ≤ {self.estoque_conjuntos.get(tipo, 0)}")

        # Restrição 2: Demanda em CONJUNTOS
        print("\n2. Restrição de demanda em CONJUNTOS:")
        for (tipo, entidade), demanda_conjuntos in self.demandas_conjuntos.items():
            var_nome = f"X_{tipo}_{entidade}"
            if var_nome in self.variaveis and demanda_conjuntos > 0:
                # Agora é direto: alocação <= demanda (ambos em conjuntos)
                self.problema += self.variaveis[var_nome] <= demanda_conjuntos, f"Demanda_Conjuntos_{tipo}_{entidade}"
                #print(f"   {tipo} para {entidade}: {var_nome} ≤ {demanda_conjuntos} conjuntos")

        print("\n3. Restrição de não-negatividade: X_ij ≥ 0 (implícita)")

    def definir_funcao_objetivo(self):
        """
        Define a função objetivo MAXIMIZANDO a alocação total ponderada
        Isso garante que todo o estoque disponível será alocado
        """
        print("\nDefinindo a função objetivo (MAXIMIZAR alocação)...")

        if self.problema is None:
            self.problema = pulp.LpProblem(self.nome_problema, pulp.LpMaximize)  # Nesse caso estamos maximizando

        expressao_objetivo = []

        for (tipo, entidade), demanda_conjuntos in self.demandas_conjuntos.items():
            peso = self.peso_prioridade.get((tipo, entidade), 1.0)
            var_nome = f"X_{tipo}_{entidade}"

            if var_nome in self.variaveis and demanda_conjuntos > 0:
                # Benefício = número de conjuntos alocados * peso
                termo = peso * self.variaveis[var_nome]
                expressao_objetivo.append(termo)

        self.problema += pulp.lpSum(expressao_objetivo), "Funcao_Objetivo_Maximizar"
        print(f"Função objetivo: max ∑ peso × (conjuntos_alocados)")
        print(f"Número de termos: {len(expressao_objetivo)}")

    def resolver(self, tempo_limite: int = 60, gap: float = 0.01) -> Dict:
        """
        Resolve o problema de otimização
        """
        print(f"\n{'='*60}")
        print("RESOLVENDO PROBLEMA DE ALOCAÇÃO DE CONJUNTOS")
        print(f"{'='*60}")

        if self.problema is None:
            self.problema = pulp.LpProblem(self.nome_problema, pulp.LpMaximize)
            self.criar_variaveis()
            self.definir_funcao_objetivo()
            self.criar_restricoes()

        solver = pulp.PULP_CBC_CMD(msg=True, timeLimit=tempo_limite, gapRel=gap)

        inicio = time.time()
        status = self.problema.solve(solver)
        self.tempo_resolucao = time.time() - inicio

        valor_objetivo = pulp.value(self.problema.objective)

        self.resultados = {
            'status': pulp.LpStatus[status],
            'tempo_resolucao': self.tempo_resolucao,
            'valor_objetivo': valor_objetivo if valor_objetivo is not None else 0,
            'alocacoes': {},
            'estatisticas': self.calcular_estatisticas()
        }

        # Coletar valores das variáveis
        for nome_var, variavel in self.variaveis.items():
            valor = pulp.value(variavel)
            if valor is not None and valor > 0:
                partes = nome_var.split('_')
                if len(partes) >= 3:
                    tipo_roupa = partes[1]
                    entidade = '_'.join(partes[2:])
                    self.resultados['alocacoes'][nome_var] = {
                        'conjuntos': valor,
                        'pecas': valor * self.tamanho_conjunto.get(tipo_roupa, 1),
                        'tipo_roupa': tipo_roupa,
                        'entidade': entidade
                    }

        return self.resultados

    def calcular_estatisticas(self) -> Dict:
      """
      Calcula estatísticas sobre a solução
      """
      # Calcular demanda total em peças a partir de demandas_conjuntos
      total_demanda_pecas = 0
      for (tipo, _), demanda_conj in self.demandas_conjuntos.items():
          total_demanda_pecas += demanda_conj * self.tamanho_conjunto.get(tipo, 1)

      total_estoque_pecas = sum(
          self.estoque_conjuntos.get(tipo, 0) * self.tamanho_conjunto.get(tipo, 1)
          for tipo in self.tipos_roupa
      )

      estatisticas = {
          'total_estoque_conjuntos': sum(self.estoque_conjuntos.values()),
          'total_estoque_pecas': total_estoque_pecas,
          'total_demanda_pecas': total_demanda_pecas,
          'total_alocado_conjuntos': 0,
          'total_alocado_pecas': 0,
          'deficit_total_pecas': 0,
          'alocacoes_por_tipo': {},
          'alocacoes_por_entidade': {}
      }

      total_alocado_conjuntos = 0
      total_alocado_pecas = 0


      for (tipo, entidade), demanda_conjuntos_val in self.demandas_conjuntos.items():
            var_nome = f"X_{tipo}_{entidade}"
            if var_nome in self.variaveis:
                valor = pulp.value(self.variaveis[var_nome])
                if valor is not None:
                    pecas_alocadas = valor * self.tamanho_conjunto.get(tipo, 1)
                    total_alocado_conjuntos += valor
                    total_alocado_pecas += pecas_alocadas

                    # Estatísticas por tipo
                    if tipo not in estatisticas['alocacoes_por_tipo']:
                        estatisticas['alocacoes_por_tipo'][tipo] = {'conjuntos': 0, 'pecas': 0}
                    estatisticas['alocacoes_por_tipo'][tipo]['conjuntos'] += valor
                    estatisticas['alocacoes_por_tipo'][tipo]['pecas'] += pecas_alocadas

                    # Estatísticas por entidade
                    if entidade not in estatisticas['alocacoes_por_entidade']:
                        estatisticas['alocacoes_por_entidade'][entidade] = {'conjuntos': 0, 'pecas': 0}
                    estatisticas['alocacoes_por_entidade'][entidade]['conjuntos'] += valor
                    estatisticas['alocacoes_por_entidade'][entidade]['pecas'] += pecas_alocadas


      estatisticas['total_alocado_conjuntos'] = total_alocado_conjuntos

      estatisticas['total_alocado_pecas'] = total_alocado_pecas

      estatisticas['deficit_total_pecas'] = total_demanda_pecas - total_alocado_pecas

      return estatisticas


def imprimir_resultados(solver):
    """
    Imprime os resultados formatados
    """
    if solver.resultados is None:
        print("❌ O problema ainda não foi resolvido!")
        return

    print(f"\n{'='*60}")
    print("📊 RESULTADOS DA OTIMIZAÇÃO (MAXIMIZANDO ALOCAÇÃO)")
    print(f"{'='*60}")
    print(f"Status: {solver.resultados['status']}")
    print(f"Valor da função objetivo (alocação ponderada): {solver.resultados.get('valor_objetivo', 0):.2f}")
    print(f"Tempo de resolução: {solver.resultados.get('tempo_resolucao', 0):.2f} segundos")

    stats = solver.resultados['estatisticas']
    print(f"\n{'─'*40}")
    print("📈 ESTATÍSTICAS GERAIS:")
    print(f"{'─'*40}")
    print(f"Total em estoque: {stats.get('total_estoque_conjuntos', 0):.0f} conjuntos")
    print(f"Total em estoque: {stats.get('total_estoque_pecas', 0):.0f} peças")
    print(f"Total demandado: {stats.get('total_demanda_pecas', 0):.0f} peças")
    print(f"Total alocado: {stats.get('total_alocado_conjuntos', 0):.0f} conjuntos")
    print(f"Total alocado: {stats.get('total_alocado_pecas', 0):.0f} peças")
    print(f"Déficit total: {stats.get('deficit_total_pecas', 0):.0f} peças")

    taxa = (stats.get('total_alocado_pecas', 0) / stats.get('total_estoque_pecas', 1) * 100)
    print(f"Taxa de utilização do estoque: {taxa:.1f}%")

    taxa_atendimento = (stats.get('total_alocado_pecas', 0) / stats.get('total_demanda_pecas', 1) * 100)
    print(f"Taxa de atendimento da demanda: {taxa_atendimento:.1f}%")

    # Alocações por tipo
    if stats.get('alocacoes_por_tipo'):
        print(f"\n{'─'*40}")
        print("👕 ALOCAÇÃO POR TIPO DE ROUPA:")
        print(f"{'─'*40}")
        for tipo, dados in sorted(stats['alocacoes_por_tipo'].items(), key=lambda x: x[1]['conjuntos'], reverse=True):
            estoque_conj = solver.estoque_conjuntos.get(tipo, 0)
            tamanho = solver.tamanho_conjunto.get(tipo, 1)
            utilizacao = (dados['conjuntos'] / estoque_conj * 100) if estoque_conj > 0 else 0
            print(f"{tipo}: {dados['conjuntos']:.0f}/{estoque_conj:.0f} conjuntos ({utilizacao:.1f}%) - {dados['pecas']:.0f} peças")

"""Função que imprime os resultados (a parte de resolução foi alocado como método dentro da classe principal)"""

# @title
def print_resultados(solver):
    """Imprime os resultados formatados"""
    if solver.resultados is None:
        print("❌ O problema ainda não foi resolvido!")
        return

    print(f"\n{'='*60}")
    print("📊 RESULTADOS DA OTIMIZAÇÃO")
    print(f"{'='*60}")
    print(f"Status: {solver.resultados['status']}")
    print(f"Valor da função objetivo: {solver.resultados.get('valor_objetivo', 0):.2f}")
    print(f"Tempo de resolução: {solver.resultados.get('tempo_resolucao', 0):.2f} segundos")

    stats = solver.resultados['estatisticas']
    print(f"\n{'─'*40}")
    print("📈 ESTATÍSTICAS GERAIS:")
    print(f"{'─'*40}")
    print(f"Total em estoque: {stats.get('total_estoque_conjuntos', 0):.0f} conjuntos")
    print(f"Total em estoque: {stats.get('total_estoque_pecas', 0):.0f} peças")
    print(f"Total demandado: {stats.get('total_demanda_pecas', 0):.0f} peças")
    print(f"Total alocado: {stats.get('total_alocado_conjuntos', 0):.0f} conjuntos")
    print(f"Total alocado: {stats.get('total_alocado_pecas', 0):.0f} peças")
    print(f"Déficit total: {stats.get('deficit_total_pecas', 0):.0f} peças")

    # Evitar divisão por zero
    total_demanda = stats.get('total_demanda_pecas', 0)
    if total_demanda > 0:
        taxa = (stats.get('total_alocado_pecas', 0) / total_demanda * 100)
        print(f"Taxa de atendimento: {taxa:.1f}%")
    else:
        print(f"Taxa de atendimento: N/A (demanda total = 0)")

    # Taxa de utilização do estoque
    total_estoque = stats.get('total_estoque_pecas', 1)
    if total_estoque > 0:
        taxa_uso = (stats.get('total_alocado_pecas', 0) / total_estoque * 100)
        print(f"Taxa de utilização do estoque: {taxa_uso:.1f}%")

"""Funções para carregar planilhas da campanha (feita com as que foram fornecidas)

Extrai as entidades, o estoque e as demandas

"""

# @title
def carregar_estoque_planilha_controle(caminho: str) -> Dict[str, Dict]:
    """
    Carrega dados de estoque a partir da planilha de controle de estoque da campanha
    """
    try:
        print("📊 Carregando planilha de estoque...")

        # Carregar a aba de movimentações (estoque1)
        df_mov = pd.read_excel(caminho, sheet_name="estoque1")

        print(f"   ✓ Aba 'estoque1' carregada com {len(df_mov)} linhas")
        print(f"   Colunas disponíveis: {list(df_mov.columns)}")

        # Verificar se as colunas necessárias existem
        col_quantidade = None
        col_operacao = None
        col_categoria = None
        col_genero = None

        # Mapear colunas
        for col in df_mov.columns:
            col_lower = str(col).lower()
            if 'quant' in col_lower and not col_operacao:
                col_quantidade = col
            elif 'opera' in col_lower or col_lower == 'd' or 'operação' in col_lower:
                col_operacao = col
            elif 'categoria' in col_lower or 'tipo' in col_lower:
                col_categoria = col
            elif 'genero' in col_lower or 'gênero' in col_lower:
                col_genero = col

        # Se não encontrou, usar as colunas padrão pelo nome exato
        if 'quantidade' in df_mov.columns:
            col_quantidade = 'quantidade'
        if 'Operação' in df_mov.columns:
            col_operacao = 'Operação'
        if 'categoria' in df_mov.columns:
            col_categoria = 'categoria'
        if 'genero' in df_mov.columns:
            col_genero = 'genero'

        print(f"   Coluna de quantidade: {col_quantidade}")
        print(f"   Coluna de operação: {col_operacao}")
        print(f"   Coluna de categoria: {col_categoria}")

        # Processar e limpar dados
        def limpar_valor(valor):
            """Converte valor para número, tratando strings vazias e NAs"""
            if pd.isna(valor):
                return 0
            if isinstance(valor, (int, float)):
                return float(valor) if not pd.isna(valor) else 0
            if isinstance(valor, str):
                valor_limpo = valor.strip()
                if valor_limpo == '' or valor_limpo == '-' or valor_limpo == '0':
                    return 0
                try:
                    return float(valor_limpo)
                except:
                    return 0
            return 0

        # Aplicar limpeza na coluna de quantidade
        df_mov['quantidade_clean'] = df_mov[col_quantidade].apply(limpar_valor)

        # Calcular estoque por categoria (em peças)
        estoque_pecas = {}
        categorias_unicas = df_mov[col_categoria].dropna().unique()

        print(f"   Processando {len(categorias_unicas)} categorias...")

        for categoria in categorias_unicas:
            if pd.isna(categoria) or str(categoria).strip() == '':
                continue

            categoria_str = str(categoria).strip()

            # Filtrar entradas e saídas
            mask_categoria = df_mov[col_categoria] == categoria

            # Calcular entradas
            mask_entrada = (mask_categoria) & (df_mov[col_operacao].astype(str).str.lower() == 'entrada')
            entradas = df_mov[mask_entrada]['quantidade_clean'].sum()

            # Calcular saídas
            mask_saida = (mask_categoria) & (df_mov[col_operacao].astype(str).str.lower() == 'saída')
            saidas = df_mov[mask_saida]['quantidade_clean'].sum()

            estoque_pecas[categoria_str] = entradas - saidas

            if entradas > 0 or saidas > 0:
                print(f"      {categoria_str}: Entradas={entradas:.0f}, Saídas={saidas:.0f}, Estoque={estoque_pecas[categoria_str]:.0f}")

        # Mapeamento de categoria para tamanho padrão do conjunto (baseado na planilha)
        tamanhos_padrao = {
            "Camiseta manga longa feminina": 40,
            "Camiseta manga longa masculina": 40,
            "Calça Jeans feminina": 20,
            "Calça Jeans masculina": 20,
            "Calça Não Jeans feminina": 20,
            "Calça Não Jeans masculina": 20,
            "Manga Curta e regata feminina": 40,
            "Manga Curta e regata masculina": 40,
            "Infantil feminina": 40,
            "Infantil masculina": 40,
            "Pré-adolescente feminina": 40,
            "Pré-adolescente masculina": 40,
            "Shorts Feminino e Saia": 20,
            "Vestido/Macacão": 40,
            "Agasalho Feminino": 10,
            "Agasalho Masculino": 10,
            "Pijama Feminino": 30,
            "Pijama Masculino": 30,
            "Shorts feminino e saia": 30,
            "Shorts masculino e bermuda": 30,
            "Sapatos Feminino": 20,
            "Sapatos Masculino": 20,
            "Acessórios Gerais": 20,
            "Acessórios de Inverno": 25,
            "Bebê": 40,
            "Meias": 30,
            "Cobertor": 5,
            "Cama, Mesa e Banho": 20,
            "Brinquedos": 10,
            "Sapatos Infanto Juvenil": 25,
            "Extragrande": 20,
            "MANGA CURTA E REGATA": 40,
            "MANGA LONGA": 40,
            "CALÇAS JEANS": 15,
            "CALÇAS NÃO JEANS": 20,
            "SHORTS E BERMUDA": 30,
            "SHORTS E SAIA": 30,
            "AGASALHO": 20,
            "PIJAMA": 30,
            "VESTIDO E MACACÃO": 40,
            "BEBÊ": 40,
            "INFANTIL (3-9)": 40,
            "PRÉ-ADOLESCENTE (10-15)": 40,
            "SAPATOS": 20,
            "SAPATOS INFANTO JUVENIL": 25,
            "ACESSÓRIOS GERAIS": 20,
            "ACESSÓRIOS DE INVERNO": 25,
            "MEIAS": 30,
            "COBERTOR": 5,
            "CAMA, MESA E BANHO": 20,
            "BRINQUEDOS": 10,
            "EXTRAGRANDE": 20
        }

        estoque_conjuntos = {}
        tamanho_conjunto = {}

        # Converter peças para conjuntos
        for categoria, pecas in estoque_pecas.items():
            # Buscar tamanho do conjunto
            tamanho = tamanhos_padrao.get(categoria, 1)

            # Ajustar tamanho baseado no nome da categoria
            if 'calça' in categoria.lower() or 'shorts' in categoria.lower() or 'saia' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'manga' in categoria.lower():
                if tamanho == 1:
                    tamanho = 40
            elif 'agasalho' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'pijama' in categoria.lower():
                if tamanho == 1:
                    tamanho = 30
            elif 'sapato' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'acessório' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'meia' in categoria.lower():
                if tamanho == 1:
                    tamanho = 30
            elif 'cobertor' in categoria.lower():
                if tamanho == 1:
                    tamanho = 5
            elif 'cama' in categoria.lower():
                if tamanho == 1:
                    tamanho = 20
            elif 'brinquedo' in categoria.lower():
                if tamanho == 1:
                    tamanho = 10

            # Calcular número de conjuntos
            if pecas > 0:
                conjuntos = int(pecas // tamanho)
                if conjuntos > 0 or pecas > 0:
                    estoque_conjuntos[categoria] = conjuntos
                    tamanho_conjunto[categoria] = tamanho
                    print(f"      {categoria}: {pecas:.0f} peças -> {conjuntos} conjuntos de {tamanho} peças")

        print(f"\n✓ Processadas {len(estoque_conjuntos)} categorias de roupa")
        print(f"  Total de conjuntos em estoque: {sum(estoque_conjuntos.values())}")
        print(f"  Total de peças em estoque: {sum(estoque_pecas.values()):.0f}")

        return {
            'estoque_conjuntos': estoque_conjuntos,
            'tamanho_conjunto': tamanho_conjunto,
            'estoque_pecas': estoque_pecas
        }

    except Exception as e:
        print(f"❌ Erro ao carregar planilha de estoque: {e}")
        import traceback
        traceback.print_exc()
        return None

def carregar_entidades_planilha_entidades(caminho: str) -> List[str]:
    """
    Carrega lista de entidades a partir da planilha de entidades da campanha
    """
    try:
        print("\n📊 Carregando planilha de entidades...")
        entidades = set()

        palavras_invalidas = [
            'não', 'sim', 'as vezes', 'caso necessário', 'autorizamos',
            'familias', 'pessoas', 'crianças', 'adolescentes', 'bebês',
            'media', 'média', 'aproximadamente', 'total', 'quantidade'
        ]

        # Carregar todas as abas
        xl = pd.ExcelFile(caminho)
        sheets = xl.sheet_names

        print(f"   Abas encontradas: {sheets}")

        for sheet in sheets:
            if sheet in ['VG_NEW', 'Informações Entidades']:
                df = pd.read_excel(caminho, sheet_name=sheet, header=1)
                print(f"   Processando aba '{sheet}' com {len(df)} linhas")

                for col in df.columns:
                    col_str = str(col)
                    # Procura APENAS colunas que são explicitamente de nome da entidade
                    if col_str.lower() in ['entidade', 'nome da entidade']:
                        for valor in df[col].dropna():
                            valor_str = str(valor).strip()
                            # Filtros para considerar apenas entidades válidas
                            if (valor_str and
                                not valor_str.startswith('=IFERROR') and
                                len(valor_str) > 5 and
                                not any(palavra in valor_str.lower() for palavra in palavras_invalidas) and
                                not valor_str.isdigit() and  # Não é apenas número
                                not valor_str.replace(' ', '').isdigit()):  # Não é "20" ou "20 familias"
                                entidades.add(valor_str)
                                print(f"      Entidade encontrada: {valor_str[:50]}")

        # Também carregar das abas de respostas
        for sheet in ['resp20252', 'resp20251', 'resp20242', 'resp20241']:
            if sheet in sheets:
                df = pd.read_excel(caminho, sheet_name=sheet)

                for col in df.columns:
                    col_str = str(col)
                    # Procura APENAS a coluna 'Nome da entidade'
                    if col_str == 'Nome da entidade':
                        for valor in df[col].dropna():
                            valor_str = str(valor).strip()
                            if (valor_str and
                                not valor_str.startswith('=IFERROR') and
                                len(valor_str) > 5 and
                                not any(palavra in valor_str.lower() for palavra in palavras_invalidas)):
                                entidades.add(valor_str)
                                print(f"      Entidade encontrada: {valor_str[:50]}")

        entidades_lista = sorted(list(entidades))
        print(f"\n✓ Total de entidades carregadas: {len(entidades_lista)}")

        if entidades_lista:
            print("   Entidades encontradas:")
            for i, ent in enumerate(entidades_lista[:20], 1):
                print(f"      {i}. {ent}")
            if len(entidades_lista) > 20:
                print(f"      ... e mais {len(entidades_lista) - 20} entidades")

        return entidades_lista

    except Exception as e:
        print(f"❌ Erro ao carregar planilha de entidades: {e}")
        import traceback
        traceback.print_exc()
        return []

def carregar_demandas_planilha_entidades(caminho: str,
                                          estoque_conjuntos: Dict[str, int],
                                          tamanho_conjunto: Dict[str, int],
                                          usar_pesos_personalizados: bool = True) -> Tuple[Dict, Dict]:
    """
    Carrega demandas e calcula pesos de prioridade personalizados
    Entidades que informaram pessoas usam 2 peças/pessoa
    Entidades que NÃO informaram usam 5 peças/pessoa (estimativa com 50 pessoas)
    """
    try:
        print("\n📊 Carregando demandas e calculando pesos das entidades...")

        xl = pd.ExcelFile(caminho)
        sheets = xl.sheet_names

        demandas_conjuntos = {}
        prioridades = {}

        PECAS_POR_PESSOA_REAL = 2      # Para entidades que informaram pessoas
        PECAS_POR_PESSOA_ESTIMADO = 5  # Para entidades que NÃO informaram
        PESSOAS_PADRAO = 50            # Valor padrão quando não informado o numero de pessoas de cada entidade

        # Mapeamento de categorias
        mapeamento_categorias = {
            'Calça jeans': ['CALÇAS JEANS', 'Calça Jeans feminina', 'Calça Jeans masculina'],
            'Calça não jeans': ['CALÇAS NÃO JEANS', 'Calça Não Jeans feminina', 'Calça Não Jeans masculina'],
            'Shorts e bermudas': ['SHORTS E BERMUDA', 'Shorts masculino e bermuda'],
            'Shorts e saia': ['SHORTS E SAIA', 'Shorts Feminino e Saia', 'Shorts feminino e saia'],
            'Agasalhos': ['AGASALHO', 'Agasalho Feminino', 'Agasalho Masculino'],
            'Manga curta e regata': ['MANGA CURTA E REGATA', 'Manga Curta e regata feminina', 'Manga Curta e regata masculina'],
            'Manga longa': ['MANGA LONGA', 'Camiseta manga longa feminina', 'Camiseta manga longa masculina'],
            'Pijamas': ['PIJAMA', 'Pijama Feminino', 'Pijama Masculino'],
            'Sapatos': ['SAPATOS', 'Sapatos Feminino', 'Sapatos Masculino'],
            'Acessórios de inverno': ['ACESSÓRIOS DE INVERNO'],
            'Meias': ['MEIAS'],
            'Cobertores': ['COBERTOR'],
            'Cama, mesa e banho': ['CAMA, MESA E BANHO'],
            'Brinquedos': ['BRINQUEDOS'],
            'Sapatos infantis': ['SAPATOS INFANTO JUVENIL'],
            'Roupas infantis': ['INFANTIL (3-9)', 'Infantil feminina', 'Infantil masculina'],
            'Roupas para bebês': ['BEBÊ'],
            'Extra grande': ['EXTRAGRANDE'],
            'Roupas para pré-adolescentes': ['PRÉ-ADOLESCENTE (10-15)', 'Pré-adolescente feminina', 'Pré-adolescente masculina'],
            'Vestidos': ['VESTIDO/MACACÃO', 'Vestido/Macacão']
        }

        # Abas de respostas
        resp_sheets = ['resp20252', 'resp20251', 'resp20242', 'resp20241']

        # Coletar todas as entidades válidas
        entidades_validas = set()
        for sheet in resp_sheets:
            if sheet in sheets:
                df = pd.read_excel(caminho, sheet_name=sheet)
                for col in df.columns:
                    if 'entidade' in str(col).lower() or 'nome' in str(col).lower():
                        for valor in df[col].dropna():
                            nome = str(valor).strip()
                            if nome and not nome.startswith('=IFERROR') and len(nome) > 5:
                                entidades_validas.add(nome)

        # Contadores para estatísticas
        entidades_com_pessoas = 0
        entidades_sem_pessoas = 0
        total_demandas_calculadas = 0

        # Processar cada aba de respostas
        for sheet in resp_sheets:
            if sheet in sheets:
                df = pd.read_excel(caminho, sheet_name=sheet)
                print(f"   Processando aba '{sheet}'...")

                # Identificar colunas
                col_entidade = None
                col_categorias = None
                col_quantidade_pessoas = None
                col_nivel_necessidade = None
                col_categorias_prioritarias = None

                for col in df.columns:
                    col_str = str(col).lower()
                    if 'entidade' in col_str and not col_entidade:
                        col_entidade = col
                    elif ('categoria' in col_str or 'roupas' in col_str) and 'necessitam' in col_str:
                        if 'mais' in col_str or 'priorit' in col_str:
                            col_categorias_prioritarias = col
                        else:
                            col_categorias = col
                    elif 'pessoas' in col_str or 'assistidas' in col_str or 'atendidas' in col_str:
                        col_quantidade_pessoas = col
                    elif ('quantidade' in col_str or 'nível' in col_str or 'necessidade' in col_str) and 'roupas' in col_str:
                        col_nivel_necessidade = col

                if not col_nivel_necessidade:
                    for col in df.columns:
                        col_str = str(col).lower()
                        if any(word in col_str for word in ['muito', 'pouco', 'necessidade', 'urgente']):
                            col_nivel_necessidade = col
                            break

                if not col_categorias_prioritarias:
                    for col in df.columns:
                        col_str = str(col).lower()
                        if any(word in col_str for word in ['priorit', 'mais precisa', 'categoria mais']):
                            col_categorias_prioritarias = col
                            break

                if col_entidade and col_categorias:
                    print(f"      Coluna entidade: {col_entidade}")
                    print(f"      Coluna nível necessidade: {col_nivel_necessidade if col_nivel_necessidade else 'Não encontrada'}")
                    print(f"      Coluna categorias prioritárias: {col_categorias_prioritarias if col_categorias_prioritarias else 'Não encontrada'}")

                    # Calcular pesos personalizados
                    if usar_pesos_personalizados and col_nivel_necessidade and col_categorias_prioritarias:
                        pesos_aba = calcular_pesos_prioridade(
                            df, col_entidade, col_nivel_necessidade,
                            col_categorias_prioritarias,
                            list(estoque_conjuntos.keys()),
                            mapeamento_categorias
                        )
                        prioridades.update(pesos_aba)

                    # Processar demandas
                    for idx, row in df.iterrows():
                        entidade = str(row[col_entidade]) if pd.notna(row[col_entidade]) else ''
                        if not entidade or entidade.startswith('=IFERROR') or len(entidade) < 5:
                            continue

                        if entidade not in entidades_validas:
                            continue

                        categorias_str = str(row[col_categorias]) if pd.notna(row[col_categorias]) else ''

                        # extraindo quantidade de pessoas da planilha
                        qtd_pessoas = 0
                        entidade_informou_pessoas = False

                        if col_quantidade_pessoas and pd.notna(row[col_quantidade_pessoas]):
                            try:
                                pessoas_str = str(row[col_quantidade_pessoas])
                                # Tenta extrair o primeiro número encontrado
                                numeros = re.findall(r'\d+', pessoas_str)
                                if numeros:
                                    qtd_pessoas = int(numeros[0])
                                    entidade_informou_pessoas = True
                            except:
                                pass


                        if entidade_informou_pessoas:
                            # Entidade informou o número de pessoas
                            pecas_por_pessoa = PECAS_POR_PESSOA_REAL
                            demanda_pecas = int(qtd_pessoas * pecas_por_pessoa)
                            tipo_demanda = "REAL"
                            entidades_com_pessoas += 1
                        else:
                            # Entidade NÃO informou - estimativa
                            qtd_pessoas = PESSOAS_PADRAO
                            pecas_por_pessoa = PECAS_POR_PESSOA_ESTIMADO
                            demanda_pecas = int(qtd_pessoas * pecas_por_pessoa)
                            tipo_demanda = "ESTIMADA"
                            entidades_sem_pessoas += 1

                        # Para cada tipo de roupa
                        for tipo_estoque in estoque_conjuntos.keys():
                            needs_match = False
                            for key, mapped_types in mapeamento_categorias.items():
                                if key in categorias_str or key.lower() in categorias_str.lower():
                                    if tipo_estoque in mapped_types or any(mt in tipo_estoque for mt in mapped_types):
                                        needs_match = True
                                        break

                            if needs_match or 'todas' in categorias_str.lower() or 'todos' in categorias_str.lower():
                                tamanho = tamanho_conjunto.get(tipo_estoque, 1)

                                # Converte peças para conjuntos (arredondando para cima)
                                demanda_conjuntos_calc = (demanda_pecas + tamanho - 1) // tamanho
                                demanda_conjuntos_calc = max(demanda_conjuntos_calc, 0)

                                chave = (tipo_estoque, entidade)

                                # Se já existe demanda para esta combinação, mantém a maior
                                if chave not in demandas_conjuntos:
                                    demandas_conjuntos[chave] = demanda_conjuntos_calc
                                    total_demandas_calculadas += 1

                                    if chave not in prioridades:
                                        prioridades[chave] = 1.0


        print(f"\n✓ Total de demandas em CONJUNTOS: {len(demandas_conjuntos)}")
        print(f"✓ Total de pesos personalizados calculados: {len(prioridades)}")
        print(f"\n📊 Estatísticas de cálculo de demanda:")
        print(f"   Entidades que INFORMARAM pessoas: {entidades_com_pessoas} (usaram {PECAS_POR_PESSOA_REAL} peças/pessoa)")
        print(f"   Entidades que NÃO informaram pessoas: {entidades_sem_pessoas} (usaram {PECAS_POR_PESSOA_ESTIMADO} peças/pessoa)")

        # Estatísticas totais
        total_demanda_conj = sum(demandas_conjuntos.values())
        total_demanda_pecas = 0
        for (tipo, _), conj in demandas_conjuntos.items():
            total_demanda_pecas += conj * tamanho_conjunto.get(tipo, 1)

        total_estoque_conj = sum(estoque_conjuntos.values())
        total_estoque_pecas = sum(estoque_conjuntos.get(tipo, 0) * tamanho_conjunto.get(tipo, 1)
                                   for tipo in estoque_conjuntos.keys())

        print(f"\n   Demanda total: {total_demanda_conj} conjuntos ({total_demanda_pecas:.0f} peças)")
        print(f"   Estoque total: {total_estoque_conj} conjuntos ({total_estoque_pecas:.0f} peças)")
        print(f"   Relação demanda/estoque: {total_demanda_conj / max(1, total_estoque_conj):.1f}x")

        return demandas_conjuntos, prioridades

    except Exception as e:
        print(f"❌ Erro ao carregar demandas: {e}")
        import traceback
        traceback.print_exc()
        return {}, {}

"""Função que calcula os pesos com base na resposta da planilha"""

# @title
def calcular_pesos_prioridade(df_resposta: pd.DataFrame,
                               col_entidade: str,
                               col_quantidade: str,
                               col_categorias: str,
                               tipos_roupa_disponiveis: List[str],
                               mapeamento_categorias: Dict) -> Dict:
    """
    Calcula pesos de prioridade baseado na necessidade da entidade

    Args:
        df_resposta: DataFrame com as respostas da entidade
        col_entidade: Nome da coluna com nome da entidade
        col_quantidade: Nome da coluna com nível de necessidade (muito/pouco)
        col_categorias: Nome da coluna com categorias mais necessitadas
        tipos_roupa_disponiveis: Lista de tipos de roupa disponíveis no estoque
        mapeamento_categorias: Mapeamento entre categorias do forms e estoque
        PESO PADRÃO = 1.0

    Returns:
        Dicionário com pesos para cada (tipo_roupa, entidade)
    """
    pesos = {}

    # Mapeamento do nível de necessidade para peso base
    # Quanto maior a necessidade, maior o peso
    peso_por_necessidade = {
        'muito': 2.5,
        'muita': 2.5,
        'alta': 2.5,
        'urgente': 3.0,
        'médio': 2.0,
        'media': 2.0,
        'média': 2.0,
        'pouco': 1.0,
        'baixa': 1.0,
        'normal': 1.5,
        'regular': 1.5
    }

    for idx, row in df_resposta.iterrows():
        entidade = str(row[col_entidade]) if pd.notna(row[col_entidade]) else ''
        if not entidade or entidade.startswith('=IFERROR') or len(entidade) < 5:
            continue

        # 1. Peso base pelo nível de necessidade
        necessidade_texto = str(row[col_quantidade]) if pd.notna(row[col_quantidade]) else 'normal'
        necessidade_texto = necessidade_texto.lower().strip()

        peso_base = 1.0  # peso padrão
        for key, value in peso_por_necessidade.items():
            if key in necessidade_texto:
                peso_base = value
                break

        # 2. Identificar categorias prioritárias da entidade
        categorias_prioritarias = str(row[col_categorias]) if pd.notna(row[col_categorias]) else ''
        categorias_prioritarias = categorias_prioritarias.lower()

        # Lista de categorias que a entidade mais precisa
        categorias_prioritarias_lista = []
        for cat_form, cat_estoque_list in mapeamento_categorias.items():
            if cat_form.lower() in categorias_prioritarias:
                categorias_prioritarias_lista.extend(cat_estoque_list)

        # 3. Calcular peso final para cada tipo de roupa
        for tipo_roupa in tipos_roupa_disponiveis:
            # Peso base pela necessidade geral
            peso_final = peso_base

            # Aumenta peso se for uma categoria prioritária para esta entidade
            if tipo_roupa in categorias_prioritarias_lista:
                # Categoria prioritária ganha peso extra
                peso_final *= 2.5
            elif any(cat in tipo_roupa.lower() for cat in ['acessório', 'brinquedo', 'cobertor']):
                # Itens complementares têm peso reduzido
                peso_final *= 1.5
            else:
                # Demais categorias mantêm peso base
                peso_final *= 1.0

            # Garantir que o peso esteja em um range razoável
            peso_final = max(1, min(5.0, peso_final))

            chave = (tipo_roupa, entidade)
            pesos[chave] = peso_final


    return pesos

"""Função executora

"""

# @title
def executar_campanha():
    """
    Executa a análise completa da campanha com pesos personalizados
    baseados nas necessidades das entidades
    """
    print("\n" + "="*60)
    print("ANÁLISE DA CAMPANHA DO AGASALHO")
    print("="*60)
    print("🎯 Usando pesos personalizados baseados nas necessidades das entidades")

    # Criar modelo (sempre com pesos personalizados)
    solver = criar_modelo_planilhas_campanha(usar_pesos_personalizados=True)

    if solver:
        print("\n" + "="*60)
        print("CONSTRUINDO E RESOLVENDO MODELO")
        print("="*60)

        # Construir e resolver
        solver.criar_variaveis()
        solver.definir_funcao_objetivo()
        solver.criar_restricoes()
        solver.resolver()

        # Mostrar os pesos utilizados (para debug/informação)
        if solver.peso_prioridade:
            print(f"\n🎯 RESUMO DOS PESOS UTILIZADOS:")
            print(f"   Total de pesos calculados: {len(solver.peso_prioridade)}")

            # Mostrar estatísticas dos pesos
            pesos_valores = list(solver.peso_prioridade.values())
            print(f"   Média dos pesos: {sum(pesos_valores)/len(pesos_valores):.2f}")
            print(f"   Peso mínimo: {min(pesos_valores):.2f}")
            print(f"   Peso máximo: {max(pesos_valores):.2f}")

            # Mostrar top 10 maiores pesos (entidades com maior prioridade)
            print(f"\n   🔥 TOP 10 - Maiores prioridades:")
            pesos_ordenados = sorted(solver.peso_prioridade.items(), key=lambda x: x[1], reverse=True)
            for i, ((tipo, entidade), peso) in enumerate(pesos_ordenados[:10], 1):
                # Limitar tamanho dos nomes para melhor visualização
                tipo_short = tipo[:35] + "..." if len(tipo) > 35 else tipo
                entidade_short = entidade[:35] + "..." if len(entidade) > 35 else entidade
                print(f"      {i}. {tipo_short} → {entidade_short}: peso = {peso:.2f}")

            if len(pesos_ordenados) > 10:
                print(f"      ... e mais {len(pesos_ordenados) - 10} pesos")

        # Imprimir resultados
        if hasattr(solver, 'imprimir_resultados'):
            solver.imprimir_resultados()
        else:
            print_resultados(solver)

        # Salvar resultados
        salvar = input("\n📥 Deseja salvar os resultados? (s/n): ").strip().lower()
        if salvar == 's':
            from datetime import datetime
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            nome_arquivo = f"resultados_campanha_{timestamp}.xlsx"

            # Criar DataFrame com resultados
            df_resultados = pd.DataFrame([
                {
                    'Variável': var,
                    'Conjuntos': dados['conjuntos'],
                    'Peças': dados['pecas'],
                    'Tipo': dados['tipo_roupa'],
                    'Entidade': dados['entidade'],
                    'Peso_Utilizado': solver.peso_prioridade.get((dados['tipo_roupa'], dados['entidade']), 1.0)
                }
                for var, dados in solver.resultados['alocacoes'].items()
                if dados['conjuntos'] > 0
            ])

            if len(df_resultados) > 0:
                df_resultados.to_excel(nome_arquivo, index=False)
                print(f"✅ Resultados salvos em: {nome_arquivo}")

                # Também salvar estatísticas
                stats = solver.resultados['estatisticas']

                # Calcular taxa de atendimento com segurança
                total_demanda = stats.get('total_demanda_pecas', 0)
                if total_demanda > 0:
                    taxa_atendimento = f"{stats.get('total_alocado_pecas', 0) / total_demanda * 100:.1f}%"
                else:
                    taxa_atendimento = "N/A (demanda = 0)"

                df_stats = pd.DataFrame([
                    {'Métrica': 'Total de conjuntos em estoque', 'Valor': stats.get('total_estoque_conjuntos', 0)},
                    {'Métrica': 'Total de peças em estoque', 'Valor': stats.get('total_estoque_pecas', 0)},
                    {'Métrica': 'Total demandado (peças)', 'Valor': stats.get('total_demanda_pecas', 0)},
                    {'Métrica': 'Total alocado (conjuntos)', 'Valor': stats.get('total_alocado_conjuntos', 0)},
                    {'Métrica': 'Total alocado (peças)', 'Valor': stats.get('total_alocado_pecas', 0)},
                    {'Métrica': 'Déficit total (peças)', 'Valor': stats.get('deficit_total_pecas', 0)},
                    {'Métrica': 'Taxa de atendimento', 'Valor': taxa_atendimento}
                ])

                nome_stats = f"estatisticas_campanha_{timestamp}.xlsx"
                df_stats.to_excel(nome_stats, index=False)
                print(f"✅ Estatísticas salvas em: {nome_stats}")

                # Salvar pesos utilizados
                df_pesos = pd.DataFrame([
                {
                    'Tipo_Roupa': tipo,
                    'Entidade': entidade,
                    'Peso_Utilizado': peso,
                    'Demanda_Conjuntos': solver.demandas_conjuntos.get((tipo, entidade), 0)
                }
                for (tipo, entidade), peso in solver.peso_prioridade.items()
            ])

            if len(df_pesos) > 0:
                # Ordenar por peso (maiores primeiro)
                df_pesos = df_pesos.sort_values('Peso_Utilizado', ascending=False)
                nome_pesos = f"pesos_utilizados_{timestamp}.xlsx"
                df_pesos.to_excel(nome_pesos, index=False)
                print(f"✅ Pesos utilizados salvos em: {nome_pesos}")
            else:
                print("⚠ Nenhuma alocação registrada para salvar")

    return solver

"""Main"""

# @title
def criar_modelo_planilhas_campanha(usar_pesos_personalizados: bool = True):
    """
    Cria modelo usando as planilhas da campanha
    Por padrão, usa pesos personalizados baseados nas necessidades das entidades
    """
    print("\n" + "="*60)
    print("CRIAÇÃO DE MODELO COM PLANILHAS DA CAMPANHA")
    print("="*60)

    # Caminhos
    print("\nForneça os caminhos dos arquivos:")
    print("1. Planilha de controle de estoque (controle estoque campanha.xlsx)")
    caminho_estoque = input("   Caminho: ").strip()

    print("2. Planilha de entidades (entidades campanha.xlsx)")
    caminho_entidades = input("   Caminho: ").strip()

    # Carregar estoque
    dados_estoque = carregar_estoque_planilha_controle(caminho_estoque)
    if not dados_estoque:
        print("❌ Erro ao carregar estoque!")
        return None

    estoque_conjuntos = dados_estoque['estoque_conjuntos']
    tamanho_conjunto = dados_estoque['tamanho_conjunto']
    tipos_roupa = list(estoque_conjuntos.keys())

    print(f"\n📦 Tipos de roupa disponíveis: {len(tipos_roupa)}")
    print(f"   Estoque total: {sum(estoque_conjuntos.values())} conjuntos")

    # Carregar entidades
    entidades = carregar_entidades_planilha_entidades(caminho_entidades)
    if not entidades:
        print("⚠ Nenhuma entidade encontrada, usando lista vazia")
        entidades = []

    # Carregar demandas com pesos personalizados ou padrão
    demandas, prioridades = carregar_demandas_planilha_entidades(
        caminho_entidades,
        estoque_conjuntos,
        tamanho_conjunto,
        usar_pesos_personalizados=usar_pesos_personalizados  # Agora True por padrão
    )

    # Se não houver demandas, criar demandas padrão
    if not demandas:
        print("\n⚠ Nenhuma demanda encontrada. Criando demandas padrão...")
        for tipo in tipos_roupa:
            for entidade in entidades[:10]:
                tamanho = tamanho_conjunto.get(tipo, 40)
                demanda_pecas = tamanho * 3
                chave = (tipo, entidade)
                demandas[chave] = demanda_pecas
                prioridades[chave] = 1.0
        print(f"   Criadas {len(demandas)} demandas padrão")

    # Criar solver
    solver = AlocacaoConjuntosSolver("Modelo_Campanha_Agasalho")

    # Definir problema
    solver.definir_problema(
        tipos_roupa=tipos_roupa,
        entidades=entidades,
        estoque_conjuntos=estoque_conjuntos,
        tamanho_conjunto=tamanho_conjunto,
        demandas_conjuntos=demandas,
        peso_prioridade=prioridades
    )

    return solver


# Executar
if __name__ == "__main__":
    executar_campanha()